### ISSUE TITLE
Unknown int-code for switch-case, can be variables with descriptive name

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-arcade-cafe#135]
https://github.com/COMP2522/project-arcade-cafe/blob/8110008582b000b3367a7f0a9fac33e44feea056/src/main/java/org/bcit/comp2522/project/MenuManager.java#L22

The switch case is just using integers which are obviously code for different cases, these could be something more descriptive instead of directly using the integers, below is an example:

public static final int STATE_START_MENU_DEFAULT = 0;
public static final int STATE_START_MENU_SCOREBOARD = 2;
public static final int STATE_GAME_OVER_MENU = 3;
public static final int STATE_PAUSE_MENU = 4;

case (STATE_START_MENU_DEFAULT):
            startMenu.draw();
            break;
case (STATE_START_MENU_SCOREBOARD):
            startMenu.drawScoreboard();
            break;
case (STATE_GAME_OVER_MENU):
            gameOverMenu.draw();
            break;
case (STATE_PAUSE_MENU):
            pauseMenu.draw();
            break;

**Comment by chosm7489** [comment]
changed all integers to descriptive name
